### ISSUE TITLE
Boxの置き場所を変更したい

### ISSUE THREAD

**Issue by hanachin** [yasslab/railstutorial_box#1]
現状だとhanachin個人のアカウントに紐づけているので
http://vagrantcloud.com/

**Comment by yasulab** [comment]
こちら YassLab アカウント作っておきます :+1:

**Comment by yasulab** [comment]
結構 Yak Shaving になりそうです... (admin@yasslab.jpを作るところから...)

**Comment by hanachin** [comment]
置きました。
https://atlas.hashicorp.com/YassLab/boxes/railstutorial32

**Comment by yasulab** [comment]
@hanachin あれ、32(bit)ってsuffixだと、Railsのバージョン番号と誤解されやすそうだからこんな感じにしませんでしたっけ? :sweat_drops: 

`hanachin/railstutorial4.0-32`

**Comment by hanachin** [comment]
@yasulab 忘れていたのでREADMEに書いていたbox名で作りました。直します。

**Comment by yasulab** [comment]
同じく starter_kit の方も修正しておきました :wrench: 

https://github.com/yasslab/railstutorialjp_starter_kit/commit/7effabcf3366b1f4e88ee92e68fde9017ebf5822

**Comment by hanachin** [comment]
作りなおしました
https://atlas.hashicorp.com/YassLab/boxes/railstutorial4.0-32

**Comment by yasulab** [comment]
ありがと〜 :blush:

**Comment by hanachin** [comment]
vagrant up出来ないのでreopenします

**Comment by hanachin** [comment]
boxを上げなおしています

**Comment by hanachin** [comment]
上げなおしてvagrant up出来ること確認出来たのでcloseします。

**Comment by yasulab** [comment]
確認お疲れ様でした〜 :hotsprings:
